{% set name = "hermes-simulator" %}
{% set version = "0.1.2b0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 38d7d5477523ed1c04933ddc8a9a3f65257a3f1445ff39edc915ae5b16729255

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - astropy
    - numba
    - numpy
    - poliastro
    - pyqt
    - scipy
    - vtk
    - mayavi
  run:
    - python
    - pip
    - astropy
    - numba
    - numpy
    - poliastro
    - pyqt
    - scipy
    - vtk
    - mayavi

about:
  home: "https://github.com/Josvth/hermes-simulator"
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "Simulator for satellite data relay systems"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - josvth
